### ISSUE TITLE
Unable to parse web site

### ISSUE THREAD

**Issue by zlababa** [ekarorgit/metadata.serialzone.cz#2]
Ahoj,
na posledním openelec me scraper vyhazuje chybu, muzete se prosim na to podivat kde by mohl byt problem.

Díky Jura 

`19:00:52.476 T:1313862560 DEBUG: FindMovie: Searching for 'Supergirl' using SerialZone.cz scraper (path: '/storage/.kodi/addons/metadata.serialzone.cz', content: 'tvshows', version: '2.5')
19:00:52.478 T:1313862560 DEBUG: scraper: CreateSearchUrl returned <url cache="SZ.hledani-Supergirl.xml">http://api.serialzone.cz/xbmc/?co=Supergirl</url>
19:00:52.480 T:1313862560 DEBUG: CurlFile::Open(0x4546b20) http://api.serialzone.cz/xbmc/?co=Supergirl
19:00:52.480 T:1313862560 INFO: easy_aquire - Created session to http://api.serialzone.cz
19:00:52.733 T:1313862560 DEBUG: Get: Using "UTF-8" charset for XML "http://api.serialzone.cz/xbmc/?co=Supergirl"
19:00:52.734 T:1313862560 ERROR: Run: Unable to parse web site
19:00:52.735 T:1313862560 ERROR: Process: Error looking up item Supergirl
19:00:52.735 T:1313862560 DEBUG: Thread VideoInfoDownloader 1313862560 terminating
19:00:52.770 T:1946718224 DEBUG: ------ Window Init (DialogConfirm.xml) ------
19:00:53.067 T:1946718224 DEBUG: ------ Window Deinit (DialogConfirm.xml) ------`

**Comment by zlababa** [comment]
koukam ze ten kod to nejak zprasilo
```
19:00:52.476 T:1313862560   DEBUG: FindMovie: Searching for 'Supergirl' using SerialZone.cz scraper (path: '/storage/.kodi/addons/metadata.serialzone.cz', content: 'tvshows', version: '2.5')
19:00:52.478 T:1313862560   DEBUG: scraper: CreateSearchUrl returned <url cache="SZ.hledani-Supergirl.xml">http://api.serialzone.cz/xbmc/?co=Supergirl</url>
19:00:52.480 T:1313862560   DEBUG: CurlFile::Open(0x4546b20) http://api.serialzone.cz/xbmc/?co=Supergirl
19:00:52.480 T:1313862560    INFO: easy_aquire - Created session to http://api.serialzone.cz
19:00:52.733 T:1313862560   DEBUG: Get: Using "UTF-8" charset for XML "http://api.serialzone.cz/xbmc/?co=Supergirl"
19:00:52.734 T:1313862560   ERROR: Run: Unable to parse web site
19:00:52.735 T:1313862560   ERROR: Process: Error looking up item Supergirl
19:00:52.735 T:1313862560   DEBUG: Thread VideoInfoDownloader 1313862560 terminating
19:00:52.770 T:1946718224   DEBUG: ------ Window Init (DialogConfirm.xml) ------
19:00:53.067 T:1946718224   DEBUG: ------ Window Deinit (DialogConfirm.xml) ------
```

**Comment by ekarorgit** [comment]
@zlababa je to jeste aktualni? Z logu to nevypada jako chyba scraperu, spis to nestahne `http://api.serialzone.cz/xbmc/?co=Supergirl`,
